spring:
  application:
    name: online_toeic_test_springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_toeic_test
    username: root
    password: 
    hikari:
      auto-commit: false
  transaction:
    rollback-on-commit-failure: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port : 8080
clientUrl:
  admin: http://localhost:8082
  examinee: http://localhost:8081
